### ISSUE TITLE
Is there any way to load the userImage from local?

### ISSUE THREAD

**Issue by charleshoong97** [adeleyeayodeji/comment_box#4]

**Comment by adeleyeayodeji** [comment]
I will enable that in the next version

**Comment by adeleyeayodeji** [comment]
Use the live version at the moment

**Comment by charleshoong97** [comment]
Thank you, but may I know when is your target release date for that version? because currently I am using your package for my live product.

**Comment by adeleyeayodeji** [comment]
Possibly this week

**Comment by charleshoong97** [comment]
Thank you, wait for your good news

**Comment by adeleyeayodeji** [comment]
Update added https://pub.dev/packages/comment_box
